#!/usr/bin/env python3
"""Materialize mycelium ecosystem git revs from components.lock + overrides.

Precedence (decision 2026-08-01): dep_overrides > components.lock pin > crate Cargo.toml default.

Writes Cargo [patch] tables under .cargo/config.toml so multi-repo CI can lockstep
to a train pin (or override WIP SHAs) without hand-editing every Cargo.toml.

Usage:
  materialize-ecosystem-deps.py \\
    --lock-ref main \\
    [--overrides '{"mycelium-runtime":"<sha>"}'] \\
    [--out .cargo/config.toml] \\
    [--resolved-json /tmp/resolved.json]

Env (optional, used when flags omitted):
  ECOSYSTEM_LOCK_REF, DEP_OVERRIDES, PACKAGE_REPO_MAP_URL, COMPONENTS_LOCK_URL
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.request
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Tuple

OWNER = "tzervas"
DEFAULT_LOCK_REPO = "mycelium-lang"
RAW = "https://raw.githubusercontent.com/{owner}/{repo}/{ref}/{path}"


def fetch(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": "mycelium-materialize/1.0"})
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            return resp.read().decode("utf-8")
    except urllib.error.HTTPError as e:
        print(f"::error::fetch failed {url}: HTTP {e.code}", file=sys.stderr)
        raise SystemExit(2) from e
    except urllib.error.URLError as e:
        print(f"::error::fetch failed {url}: {e}", file=sys.stderr)
        raise SystemExit(2) from e


def parse_lock(text: str) -> Dict[str, str]:
    """Parse components.lock lines: name=sha [tree=...]"""
    pins: Dict[str, str] = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m = re.match(r"^([A-Za-z0-9._-]+)=([0-9a-f]{7,40})\b", line)
        if not m:
            continue
        pins[m.group(1)] = m.group(2)
    if not pins:
        print("::error::components.lock produced zero pins", file=sys.stderr)
        raise SystemExit(2)
    return pins


def load_package_map(text: str) -> Dict[str, str]:
    data = json.loads(text)
    out: Dict[str, str] = {}
    for entry in data.get("packages", []):
        pkg = entry["package"]
        repo = entry["repo"]
        out[pkg] = repo
    if not out:
        print("::error::empty package map", file=sys.stderr)
        raise SystemExit(2)
    return out


def multi_crate_from_map(pkg_to_repo: Dict[str, str]) -> Dict[str, List[str]]:
    repo_to_pkgs: Dict[str, List[str]] = defaultdict(list)
    for pkg, repo in sorted(pkg_to_repo.items()):
        repo_to_pkgs[repo].append(pkg)
    return dict(repo_to_pkgs)


def resolve(
    lock: Dict[str, str],
    overrides: Dict[str, str],
    pkg_to_repo: Dict[str, str],
) -> Tuple[Dict[str, str], Dict[str, List[str]]]:
    """Return repo->rev and repo->packages after overrides."""
    # Validate override keys are lock pins (repos), not packages
    for key in overrides:
        if key not in lock and key not in set(pkg_to_repo.values()):
            print(
                f"::error::dep_overrides key '{key}' is not a known lock pin / repo",
                file=sys.stderr,
            )
            raise SystemExit(2)

    repo_rev: Dict[str, str] = dict(lock)
    for pin, rev in overrides.items():
        if not re.fullmatch(r"[0-9a-f]{7,40}", rev):
            print(f"::error::override rev for {pin} is not a git sha: {rev}", file=sys.stderr)
            raise SystemExit(2)
        repo_rev[pin] = rev
        print(f"override {pin} -> {rev}")

    # Ensure every package's repo has a rev
    for pkg, repo in pkg_to_repo.items():
        if repo not in repo_rev:
            # package map may include only multi members; skip unknown
            continue

    by_repo = multi_crate_from_map(pkg_to_repo)
    return repo_rev, by_repo


def render_patch(repo_rev: Dict[str, str], by_repo: Dict[str, List[str]]) -> str:
    lines = [
        "# AUTO-GENERATED by materialize-ecosystem-deps.py — do not hand-edit",
        "# Precedence: dep_overrides > components.lock > Cargo.toml git rev defaults",
        "",
    ]
    for repo in sorted(by_repo.keys()):
        if repo not in repo_rev:
            continue
        rev = repo_rev[repo]
        url = f"https://github.com/{OWNER}/{repo}"
        pkgs = by_repo[repo]
        lines.append(f'[patch."{url}"]')
        for pkg in pkgs:
            lines.append(f'{pkg} = {{ git = "{url}", rev = "{rev}" }}')
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--lock-ref", default=os.environ.get("ECOSYSTEM_LOCK_REF", "main"))
    p.add_argument("--lock-repo", default=DEFAULT_LOCK_REPO)
    p.add_argument(
        "--overrides",
        default=os.environ.get("DEP_OVERRIDES", "{}"),
        help='JSON object { "mycelium-runtime": "<sha>", ... } keyed by lock pin',
    )
    p.add_argument(
        "--out",
        default=".cargo/config.toml",
        help="Path to write Cargo config with [patch] tables",
    )
    p.add_argument(
        "--resolved-json",
        default="",
        help="Optional path to write resolved pin map JSON for job summary",
    )
    p.add_argument(
        "--lock-url",
        default="",
        help="Override components.lock URL (tests)",
    )
    p.add_argument(
        "--map-url",
        default="",
        help="Override PACKAGE_REPO_MAP.json URL (tests)",
    )
    p.add_argument(
        "--local-lock",
        default="",
        help="Read lock from local path instead of network",
    )
    p.add_argument(
        "--local-map",
        default="",
        help="Read package map from local path instead of network",
    )
    args = p.parse_args()

    if not args.lock_ref and not args.local_lock:
        print("ecosystem lock ref empty — nothing to materialize (ok)")
        return

    if args.local_lock:
        lock_text = Path(args.local_lock).read_text(encoding="utf-8")
    else:
        lock_url = args.lock_url or RAW.format(
            owner=OWNER, repo=args.lock_repo, ref=args.lock_ref, path="components.lock"
        )
        print(f"fetch lock {lock_url}")
        lock_text = fetch(lock_url)

    if args.local_map:
        map_text = Path(args.local_map).read_text(encoding="utf-8")
    else:
        map_url = args.map_url or RAW.format(
            owner=OWNER,
            repo=args.lock_repo,
            ref=args.lock_ref,
            path="docs/PACKAGE_REPO_MAP.json",
        )
        print(f"fetch map {map_url}")
        map_text = fetch(map_url)

    try:
        overrides = json.loads(args.overrides or "{}")
    except json.JSONDecodeError as e:
        print(f"::error::dep_overrides is not valid JSON: {e}", file=sys.stderr)
        raise SystemExit(2) from e
    if not isinstance(overrides, dict):
        print("::error::dep_overrides must be a JSON object", file=sys.stderr)
        raise SystemExit(2)

    lock = parse_lock(lock_text)
    pkg_to_repo = load_package_map(map_text)
    repo_rev, by_repo = resolve(lock, overrides, pkg_to_repo)

    # Only patch repos that appear as git deps for the train (all pins)
    patch_text = render_patch(repo_rev, by_repo)

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    # If config exists, replace only our auto block or append carefully.
    # For CI we overwrite a dedicated file and instruct cargo via CARGO_HOME fragment:
    # writing .cargo/config.toml is standard.
    if out.exists():
        existing = out.read_text(encoding="utf-8")
        if "AUTO-GENERATED by materialize-ecosystem-deps" not in existing:
            # Preserve non-generated content above our block
            patch_text = existing.rstrip() + "\n\n" + patch_text
    out.write_text(patch_text, encoding="utf-8")
    print(f"wrote {out} ({len(repo_rev)} pins, {sum(len(v) for v in by_repo.values())} packages)")

    if args.resolved_json:
        payload = {
            "lock_ref": args.lock_ref,
            "overrides": overrides,
            "repo_rev": repo_rev,
            "packages_by_repo": by_repo,
        }
        Path(args.resolved_json).write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")

    # GitHub step summary
    summary = os.environ.get("GITHUB_STEP_SUMMARY")
    if summary:
        with open(summary, "a", encoding="utf-8") as fh:
            fh.write("### Ecosystem deps materialized\n\n")
            fh.write(f"- lock_ref: `{args.lock_ref}`\n")
            fh.write(f"- overrides: `{json.dumps(overrides)}`\n")
            fh.write(f"- pins: {len(repo_rev)}\n\n")
            if overrides:
                fh.write("| pin | rev |\n|---|---|\n")
                for k, v in sorted(overrides.items()):
                    fh.write(f"| `{k}` | `{v}` |\n")


if __name__ == "__main__":
    main()
